git:
  submodules: false
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git submodule update --init --recursive
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
notifications:
  email: travis-ci@zeroc.com
